### ISSUE TITLE
How can this work with Group_assign plugin?

### ISSUE THREAD

**Issue by aljawaid** [creecros/TemplateTitle#2]
This seems to conflict with the metamagik plugin, any way to resolve? it doesnt pre-fill the template title.

**Comment by creecros** [comment]
if I get a chance I'll look into it, im not seeing anything obvious at a quick glance. I don't see any conflicting overrides...but I'll run some tests.

**Comment by creecros** [comment]
So I just performed a test, and had no issue in either Task Creation or Modification.

Nor is there any errors in the logs. 

I see no issue, are you sure it's metaMagik?

**Comment by aljawaid** [comment]
> So I just performed a test, and had no issue in either Task Creation or Modification.
> 
> Nor is there any errors in the logs.
> 
> I see no issue, are you sure it's metaMagik?

I think it is group assign plugin

**Comment by creecros** [comment]
yes, that makes sense. they both override the same 2 templates.

**Comment by creecros** [comment]
the short answer is, you need to account for both plugins in both those templates, because you can't override a template twice, only one plugin will take precedence. since they both are my plugins it's easy for me to do, but it will require updates to both plugins.

**Comment by creecros** [comment]
ok, all set, you will have to update both plugins from the master repository, until i get time to make new releases.

**Comment by aljawaid** [comment]
Thank you so much for this
