### ISSUE TITLE
Do you prefer master or main?

### ISSUE THREAD

**Issue by aljawaid** [creecros/TemplateTitle#4]
Do you mind changing the branch back to `master` or do you prefer it to be `main`?

I prefer it to be `master`, I don't get politics involved with code lol

**Comment by aljawaid** [comment]
Also, if you could disable the Wiki and Actions, I'd appreciate it.... it's in the repo settings.... or increase my access level so I can do it myself.

**Comment by aljawaid** [comment]
Thoughts.... PredefinedContentManager as new (this) plugin title
- you already done the template title bit
- i can create a settings page for the labels
- i already have a hardcoded template to show the new table and classes... just need to add the labels

what do you think? or keep this as template title and create a new plugin to do all the above?

**Comment by creecros** [comment]
doesn't matter to me what the branch is called, doesn't effect me at all.

I have no idea how to increase your permissions.

**Comment by aljawaid** [comment]
OK I will leave this as it is and play around on a new plugin. See where it goes.

**Comment by creecros** [comment]
i cant find the wiki settings, but everything else should be changed

**Comment by aljawaid** [comment]
cool thanks
